server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pragma
    username: root
    password: admin
    initialize: true
    initialization-mode: always
  application:
    name: plazoleta-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    envers:
      store_data_at_delete: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"

hystrix:
  shareSecurityContext: true
feign:
  hystrix:
    enabled: true