server:
  port: 8082

spring:
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
    initialize: true
    initialization-mode: always
  application:
    name: plazoleta-service
  config:
    import: aws-parameterstore:/config/plazoleta-service/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    envers:
      store_data_at_delete: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
phoneNumber: "+573046407201"
message: "Good morning, sir, your order is ready to be picked up. Remember to show the following pin code: "
canceledOrderMessage: "Sorry, your order is already being prepared and cannot be canceled"

hystrix:
  shareSecurityContext: true
feign:
  hystrix:
    enabled: true
aws:
  paramstore:
    name: plazoleta-service
    prefix: /config
    enabled: true
    defaultContext: application
    profileSeparator: _
cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false