server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://pragma.c49io0lfc7sb.us-east-1.rds.amazonaws.com:3306/pragma
    username: admin
    password: 1051822857m
    initialize: true
    initialization-mode: always
  application:
    name: plazoleta-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    envers:
      store_data_at_delete: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
phoneNumber: "+573046407201"
message: "Good morning, sir, your order is ready to be picked up. Remember to show the following pin code: "
canceledOrderMessage: "Sorry, your order is already being prepared and cannot be canceled"

hystrix:
  shareSecurityContext: true
feign:
  hystrix:
    enabled: true